# Generated by Django 2.0.2 on 2018-02-28 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('weekly_goal', models.IntegerField()),
                ('total_time_spent', models.IntegerField()),
                ('created_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Skill',
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('created_date', models.DateField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app.Skill')),
            ],
            options={
                'ordering': ('-created_date',),
                'verbose_name_plural': 'Time Entries',
                'db_table': 'TimeEntry',
            },
        ),
    ]
