# Generated by Django 2.0.2 on 2018-02-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('created_date', models.DateField()),
            ],
            options={
                'db_table': 'TimeEntry',
            },
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Skill'),
        ),
    ]
