# Generated by Django 2.0.2 on 2018-02-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_timeentry_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='weekly_goal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
