# Generated by Django 2.0.2 on 2018-02-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_skill_weekly_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='total_time_spent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
