# Generated by Django 2.0.2 on 2018-02-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_skill_total_time_spent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ('-created_date',), 'verbose_name_plural': 'Time Entries'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
