# Generated by Django 2.0.2 on 2018-02-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180221_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='created_date',
            field=models.DateField(),
        ),
    ]
