# Generated by Django 2.0.2 on 2018-02-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180221_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
